[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ilya", email = "push.3124567890@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "pyautogui>=0.9.54",
    "qrcode>=8.2",
    "uvicorn>=0.35.0",
]

[project.scripts]
server = "server.main:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
